apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-model-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com'
    targetRevision: HEAD
    path: infrastructure/manifests/ai-models
  destination:
    server: 'https://default.svc'
    namespace: kserve-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
